#!/usr/bin/env python3

import colors as c
print(c.clear)
print(c.red + '''
STOP. ANSWER MY QUESTIONS TO CROSS THE BRIDGE OF DEATH.
HOOGA BALOOGA

''')

name = input(c.blue + '''
VWHAT IS YOUR NAME
''' + c.reset)
name = name.lower().strip()

quest = input(c.magenta + '''
VWHAT IS YOUR QUEST
''' + c.reset)

if name in ['lancelot','galahad']:

    color = input(c.orange + '''
    VWHAT IS YOU FAVORITE COLOUR
    ''' + c.reset)
    
