#!/usr/bin/env python3
cyan ='\033[0;36m'
red = '\033[0;31m'
blue = '\033[0;34p'
yellow = '\033[0;33m'
green = '\033[0;32m'
violet = '\033[1;35m'
magenta = '\033[0;35m'
orange = '\033[1;31m'
base03 = '\033[1;30m'
base02 = '\033[0;30m'
base01 = '\033[1;32m'
base00 = '\033[1;33m'
base0 = '\033[1;34m'
base1 = '\033[1;36m'
base2 = '\033[0;37m'
base3 = '\033[1;37m'
print(cyan + 'i ' + yellow + ' like ' + magenta + ' the ' ' color ' ' blue ')
print(red + 'hello ' + blue + ' world ')
