#!/usr/bin/env python3

import colors as c
from utils import ask

text = ''' I Like Candy

Hi i love candy. My favorite candy is {Type of Candy}.
My least favorite candy is {Type of Candy}. I saw lots of {Adjective1}
in the candy store yesterday. I couldnt beleive that the {Candy shop starting with 'the'}.
If there was no {Favorite Candy} i dont think i could live.
'''

lines = text.splitlines()
title = lines [0]
text = "/n".join(lines[1:])

print(c.clear + c.base3 + title + c.reset)

words = {
    "Type of Candy" : None,
    "Type of Candy" : None,
    "adjective1" : None,
    "candy shop starting with 'the'" : None,
    "Favorite Candy" : None

}

for key in words:
    words[key] = c.magenta + ask(key.rstrip('0123456789') + ': ') + c.reset

print(c.clear + c.base3  + title + c.reset)
print(text.format(**words))
