#!/usr/bin/env python3

import colors as c
import time

seconds = 0

while True:
    print(c.clear)
    print(c.cyan + '[Control-C to stop]: ' + c.reset) 
    print(seconds)
    time.sleep(0.01)
    seconds +=  1   
