#!/usr/bin/env python3

import time
import colors as c

seconds = 0
hundreths = 0

while True:
    print(c.clear + c.cyan + c.reset, end=': ')
    print(seconds, end=':')
    print(hundreths)
    time.sleep(0.01)
    hundreths += 1
    if hundreths >= 100:
        hundreths = hundreths % 100
        seconds += 1
